services:
  postgres:
    image: postgres:15
    container_name: my-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret123
      POSTGRES_DB: workshop
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - db-network

  pgadmin:
    image: dpage/pgadmin4:7.8
    container_name: my-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@workshop.com
      PGADMIN_DEFAULT_PASSWORD: secret123
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - db-network
    depends_on:
      - postgres

volumes:
  postgres_data:
  pgadmin_data:

networks:
  db-network:
